apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mynginxapp
    app.kubernetes.io/managed-by: Helm
  name: nginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.deployment_name }}
  type: NodePort
status:
  loadBalancer: {}
